# import

In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# data

In [2]:
t_c=[0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u=[35.7, 55.9, 58.2, 81.9, 56.3, 28.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c=torch.tensor(t_c)
t_u=torch.tensor(t_u)

In [3]:
#plt.plot(t_c.numpy(),t_u.numpy())
#plt.show()

# model, loss function

In [4]:
def model(t_u,w,b): #입력 텐서, 가중치, 바이어스
    return w*t_u+b  # 행렬 곱 연산은 텐서를 반환하기 위해 브로드 캐스팅을 사용함

In [5]:
def loss_fn(t_p,t_c):  # 평균 제곱 손실 msl
    squared_diffs=(t_p-t_c)**2
    return squared_diffs.mean() 

# weight, bias

In [6]:
w=torch.ones(())
b=torch.zeros(())

In [7]:
t_p=model(t_u,w,b)
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 28.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

# gradient descent

In [8]:
delta=0.1
loss_rate_of_change_w=(loss_fn(model(t_u, w+delta, b),t_c)- loss_fn(model(t_u,w-delta,b),t_c))/(2.0*delta) 
# 손실의 변화의 비율에 따라 값이 줄어들면 가중치를 늘리고, 값이 커지면 가중치를 줄임

In [9]:
learning_rate=1e-2
w=w-learning_rate * loss_rate_of_change_w
# 가중치를 업데이트함

In [10]:
loss_rate_of_change_b=(loss_fn(model(t_u,w,b+delta),t_c)-loss_fn(model(t_u,w,b-delta),t_c))/(2.0*delta)

b=b-learning_rate * loss_rate_of_change_b
# 바이어스를 업데이트함

In [11]:
def dloss_fn(t_p,t_c):
    dsq_diffs=2 * (t_p-t_c)/t_p.size(0) # 평균의 도함수로 나눴음
    return dsq_diffs

In [12]:
def dmodel_dw(t_u,w,b):
    return t_u

In [13]:
def dmodel_db(t_u,w,b):
    return 1.0

In [14]:
# 경사함수 정의
def grad_fn(t_u,t_c,t_p,w,b):
    dloss_dtp=dloss_fn(t_p,t_c)
    dloss_dw=dloss_dtp*dmodel_dw(t_u,w,b)
    dloss_db=dloss_dtp*dmodel_db(t_u,w,b)
    return torch.stack([dloss_dw.sum(), dloss_db.sum()]) 
# 합 계산은 파라미터를 모델의 전체 입력 벡터에 대해 적용하던 브로드캐스팅의 역순

# train

In [15]:
def training_loop(n_epochs, learning_rate,params,t_u,t_c):
    for epoch in range(1, n_epochs+1):
        w,b=params
        
        t_p=model(t_u,w,b) # 순방향 전달
        loss=loss_fn(t_p,t_c)
        grad=grad_fn(t_u,t_c,t_p,w,b) # 역방향 전달
        
        params=params-learning_rate * grad
        
        print('Epoch %d, Loss %f' % (epoch,float(loss)))
    
    return params

In [16]:
training_loop(
n_epochs=100,
learning_rate=1e-4,
params=torch.tensor([1.0,0.0]),
t_u=t_u,
t_c=t_c)

Epoch 1, Loss 1651.521118
Epoch 2, Loss 342.352905
Epoch 3, Loss 88.951729
Epoch 4, Loss 39.903183
Epoch 5, Loss 30.408772
Epoch 6, Loss 28.570398
Epoch 7, Loss 28.213917
Epoch 8, Loss 28.144270
Epoch 9, Loss 28.130138
Epoch 10, Loss 28.126751
Epoch 11, Loss 28.125456
Epoch 12, Loss 28.124550
Epoch 13, Loss 28.123724
Epoch 14, Loss 28.122919
Epoch 15, Loss 28.122118
Epoch 16, Loss 28.121313
Epoch 17, Loss 28.120502
Epoch 18, Loss 28.119701
Epoch 19, Loss 28.118902
Epoch 20, Loss 28.118090
Epoch 21, Loss 28.117290
Epoch 22, Loss 28.116488
Epoch 23, Loss 28.115681
Epoch 24, Loss 28.114876
Epoch 25, Loss 28.114073
Epoch 26, Loss 28.113274
Epoch 27, Loss 28.112471
Epoch 28, Loss 28.111662
Epoch 29, Loss 28.110863
Epoch 30, Loss 28.110054
Epoch 31, Loss 28.109253
Epoch 32, Loss 28.108454
Epoch 33, Loss 28.107643
Epoch 34, Loss 28.106842
Epoch 35, Loss 28.106035
Epoch 36, Loss 28.105236
Epoch 37, Loss 28.104437
Epoch 38, Loss 28.103626
Epoch 39, Loss 28.102825
Epoch 40, Loss 28.102022
Epoch 

tensor([ 0.2392, -0.0419])

In [17]:
t_un=0.1* t_u

In [18]:
training_loop(
n_epochs=100,
learning_rate=1e-2,
params=torch.tensor([1.0,0.0]),
t_u=t_un,
t_c=t_c)

Epoch 1, Loss 81.858887
Epoch 2, Loss 38.226109
Epoch 3, Loss 30.381672
Epoch 4, Loss 28.917381
Epoch 5, Loss 28.590729
Epoch 6, Loss 28.467157
Epoch 7, Loss 28.380054
Epoch 8, Loss 28.299721
Epoch 9, Loss 28.220875
Epoch 10, Loss 28.142561
Epoch 11, Loss 28.064598
Epoch 12, Loss 27.986977
Epoch 13, Loss 27.909679
Epoch 14, Loss 27.832697
Epoch 15, Loss 27.756044
Epoch 16, Loss 27.679707
Epoch 17, Loss 27.603685
Epoch 18, Loss 27.527979
Epoch 19, Loss 27.452595
Epoch 20, Loss 27.377520
Epoch 21, Loss 27.302757
Epoch 22, Loss 27.228310
Epoch 23, Loss 27.154173
Epoch 24, Loss 27.080345
Epoch 25, Loss 27.006817
Epoch 26, Loss 26.933599
Epoch 27, Loss 26.860689
Epoch 28, Loss 26.788086
Epoch 29, Loss 26.715776
Epoch 30, Loss 26.643770
Epoch 31, Loss 26.572069
Epoch 32, Loss 26.500664
Epoch 33, Loss 26.429554
Epoch 34, Loss 26.358740
Epoch 35, Loss 26.288221
Epoch 36, Loss 26.218004
Epoch 37, Loss 26.148066
Epoch 38, Loss 26.078432
Epoch 39, Loss 26.009081
Epoch 40, Loss 25.940016
Epoch 41,

tensor([ 2.7869, -2.2923])

In [19]:
params=training_loop(
n_epochs=5000,
learning_rate=1e-2,
params=torch.tensor([1.0,0.0]),
t_u=t_un,
t_c=t_c,
)
params

Epoch 1, Loss 81.858887
Epoch 2, Loss 38.226109
Epoch 3, Loss 30.381672
Epoch 4, Loss 28.917381
Epoch 5, Loss 28.590729
Epoch 6, Loss 28.467157
Epoch 7, Loss 28.380054
Epoch 8, Loss 28.299721
Epoch 9, Loss 28.220875
Epoch 10, Loss 28.142561
Epoch 11, Loss 28.064598
Epoch 12, Loss 27.986977
Epoch 13, Loss 27.909679
Epoch 14, Loss 27.832697
Epoch 15, Loss 27.756044
Epoch 16, Loss 27.679707
Epoch 17, Loss 27.603685
Epoch 18, Loss 27.527979
Epoch 19, Loss 27.452595
Epoch 20, Loss 27.377520
Epoch 21, Loss 27.302757
Epoch 22, Loss 27.228310
Epoch 23, Loss 27.154173
Epoch 24, Loss 27.080345
Epoch 25, Loss 27.006817
Epoch 26, Loss 26.933599
Epoch 27, Loss 26.860689
Epoch 28, Loss 26.788086
Epoch 29, Loss 26.715776
Epoch 30, Loss 26.643770
Epoch 31, Loss 26.572069
Epoch 32, Loss 26.500664
Epoch 33, Loss 26.429554
Epoch 34, Loss 26.358740
Epoch 35, Loss 26.288221
Epoch 36, Loss 26.218004
Epoch 37, Loss 26.148066
Epoch 38, Loss 26.078432
Epoch 39, Loss 26.009081
Epoch 40, Loss 25.940016
Epoch 41,

Epoch 1078, Loss 9.646799
Epoch 1079, Loss 9.645898
Epoch 1080, Loss 9.645000
Epoch 1081, Loss 9.644102
Epoch 1082, Loss 9.643210
Epoch 1083, Loss 9.642323
Epoch 1084, Loss 9.641438
Epoch 1085, Loss 9.640558
Epoch 1086, Loss 9.639683
Epoch 1087, Loss 9.638810
Epoch 1088, Loss 9.637940
Epoch 1089, Loss 9.637074
Epoch 1090, Loss 9.636210
Epoch 1091, Loss 9.635352
Epoch 1092, Loss 9.634494
Epoch 1093, Loss 9.633645
Epoch 1094, Loss 9.632796
Epoch 1095, Loss 9.631951
Epoch 1096, Loss 9.631111
Epoch 1097, Loss 9.630275
Epoch 1098, Loss 9.629437
Epoch 1099, Loss 9.628608
Epoch 1100, Loss 9.627780
Epoch 1101, Loss 9.626956
Epoch 1102, Loss 9.626138
Epoch 1103, Loss 9.625319
Epoch 1104, Loss 9.624505
Epoch 1105, Loss 9.623696
Epoch 1106, Loss 9.622889
Epoch 1107, Loss 9.622086
Epoch 1108, Loss 9.621285
Epoch 1109, Loss 9.620488
Epoch 1110, Loss 9.619697
Epoch 1111, Loss 9.618904
Epoch 1112, Loss 9.618118
Epoch 1113, Loss 9.617335
Epoch 1114, Loss 9.616554
Epoch 1115, Loss 9.615777
Epoch 1116, 

Epoch 1590, Loss 9.455599
Epoch 1591, Loss 9.455494
Epoch 1592, Loss 9.455387
Epoch 1593, Loss 9.455282
Epoch 1594, Loss 9.455176
Epoch 1595, Loss 9.455070
Epoch 1596, Loss 9.454969
Epoch 1597, Loss 9.454864
Epoch 1598, Loss 9.454759
Epoch 1599, Loss 9.454656
Epoch 1600, Loss 9.454556
Epoch 1601, Loss 9.454452
Epoch 1602, Loss 9.454350
Epoch 1603, Loss 9.454248
Epoch 1604, Loss 9.454147
Epoch 1605, Loss 9.454046
Epoch 1606, Loss 9.453948
Epoch 1607, Loss 9.453846
Epoch 1608, Loss 9.453748
Epoch 1609, Loss 9.453650
Epoch 1610, Loss 9.453549
Epoch 1611, Loss 9.453454
Epoch 1612, Loss 9.453357
Epoch 1613, Loss 9.453259
Epoch 1614, Loss 9.453161
Epoch 1615, Loss 9.453065
Epoch 1616, Loss 9.452969
Epoch 1617, Loss 9.452872
Epoch 1618, Loss 9.452778
Epoch 1619, Loss 9.452685
Epoch 1620, Loss 9.452590
Epoch 1621, Loss 9.452496
Epoch 1622, Loss 9.452400
Epoch 1623, Loss 9.452308
Epoch 1624, Loss 9.452214
Epoch 1625, Loss 9.452125
Epoch 1626, Loss 9.452031
Epoch 1627, Loss 9.451941
Epoch 1628, 

Epoch 2132, Loss 9.432685
Epoch 2133, Loss 9.432675
Epoch 2134, Loss 9.432665
Epoch 2135, Loss 9.432654
Epoch 2136, Loss 9.432644
Epoch 2137, Loss 9.432631
Epoch 2138, Loss 9.432620
Epoch 2139, Loss 9.432610
Epoch 2140, Loss 9.432598
Epoch 2141, Loss 9.432590
Epoch 2142, Loss 9.432578
Epoch 2143, Loss 9.432565
Epoch 2144, Loss 9.432557
Epoch 2145, Loss 9.432548
Epoch 2146, Loss 9.432536
Epoch 2147, Loss 9.432524
Epoch 2148, Loss 9.432514
Epoch 2149, Loss 9.432504
Epoch 2150, Loss 9.432495
Epoch 2151, Loss 9.432484
Epoch 2152, Loss 9.432472
Epoch 2153, Loss 9.432465
Epoch 2154, Loss 9.432454
Epoch 2155, Loss 9.432446
Epoch 2156, Loss 9.432433
Epoch 2157, Loss 9.432424
Epoch 2158, Loss 9.432411
Epoch 2159, Loss 9.432403
Epoch 2160, Loss 9.432392
Epoch 2161, Loss 9.432384
Epoch 2162, Loss 9.432373
Epoch 2163, Loss 9.432364
Epoch 2164, Loss 9.432353
Epoch 2165, Loss 9.432344
Epoch 2166, Loss 9.432334
Epoch 2167, Loss 9.432323
Epoch 2168, Loss 9.432316
Epoch 2169, Loss 9.432305
Epoch 2170, 

Epoch 3208, Loss 9.430055
Epoch 3209, Loss 9.430053
Epoch 3210, Loss 9.430054
Epoch 3211, Loss 9.430054
Epoch 3212, Loss 9.430056
Epoch 3213, Loss 9.430053
Epoch 3214, Loss 9.430055
Epoch 3215, Loss 9.430055
Epoch 3216, Loss 9.430052
Epoch 3217, Loss 9.430053
Epoch 3218, Loss 9.430053
Epoch 3219, Loss 9.430053
Epoch 3220, Loss 9.430053
Epoch 3221, Loss 9.430053
Epoch 3222, Loss 9.430054
Epoch 3223, Loss 9.430050
Epoch 3224, Loss 9.430053
Epoch 3225, Loss 9.430055
Epoch 3226, Loss 9.430054
Epoch 3227, Loss 9.430052
Epoch 3228, Loss 9.430052
Epoch 3229, Loss 9.430051
Epoch 3230, Loss 9.430052
Epoch 3231, Loss 9.430051
Epoch 3232, Loss 9.430053
Epoch 3233, Loss 9.430050
Epoch 3234, Loss 9.430053
Epoch 3235, Loss 9.430053
Epoch 3236, Loss 9.430051
Epoch 3237, Loss 9.430052
Epoch 3238, Loss 9.430052
Epoch 3239, Loss 9.430050
Epoch 3240, Loss 9.430050
Epoch 3241, Loss 9.430051
Epoch 3242, Loss 9.430050
Epoch 3243, Loss 9.430049
Epoch 3244, Loss 9.430051
Epoch 3245, Loss 9.430050
Epoch 3246, 

Epoch 4192, Loss 9.430025
Epoch 4193, Loss 9.430023
Epoch 4194, Loss 9.430024
Epoch 4195, Loss 9.430024
Epoch 4196, Loss 9.430025
Epoch 4197, Loss 9.430025
Epoch 4198, Loss 9.430026
Epoch 4199, Loss 9.430027
Epoch 4200, Loss 9.430025
Epoch 4201, Loss 9.430024
Epoch 4202, Loss 9.430025
Epoch 4203, Loss 9.430025
Epoch 4204, Loss 9.430027
Epoch 4205, Loss 9.430024
Epoch 4206, Loss 9.430024
Epoch 4207, Loss 9.430025
Epoch 4208, Loss 9.430025
Epoch 4209, Loss 9.430025
Epoch 4210, Loss 9.430026
Epoch 4211, Loss 9.430025
Epoch 4212, Loss 9.430022
Epoch 4213, Loss 9.430023
Epoch 4214, Loss 9.430024
Epoch 4215, Loss 9.430026
Epoch 4216, Loss 9.430024
Epoch 4217, Loss 9.430024
Epoch 4218, Loss 9.430023
Epoch 4219, Loss 9.430025
Epoch 4220, Loss 9.430024
Epoch 4221, Loss 9.430024
Epoch 4222, Loss 9.430024
Epoch 4223, Loss 9.430024
Epoch 4224, Loss 9.430024
Epoch 4225, Loss 9.430024
Epoch 4226, Loss 9.430025
Epoch 4227, Loss 9.430023
Epoch 4228, Loss 9.430024
Epoch 4229, Loss 9.430026
Epoch 4230, 

tensor([  4.7414, -13.1984])

In [ ]:
%matplotlib inline
from matplotlib import pyplot as plt

t_p=model(t_un,*params) # 단위를 모르는 값을 정규화하여 훈련라며 인자를 언패킹함
fig=plt.figure(dpi=600)
plt.xlabel("Temperature(F)")
plt.ylabel("Temperature(C)")
plt.plot(t_u.numpy(),t_p.detach().numpy())
plt.plot(t_u.numpy(),t_c.numpy(),'o')

In [1]:
sns.scatterplot(x=t_u.numpy(),y=t_p.detach())

NameError: name 'sns' is not defined